import { mutation } from "./_generated/server";

export const seedSampleData = mutation({
  args: {},
  handler: async (ctx) => {
    // Check if data already exists
    const existingData = await ctx.db.query("auctionSheets").first();
    if (existingData) {
      return { message: "Sample data already exists" };
    }

    const sampleAuctionSheets = [
      {
        lotNumber: "1296",
        auctionHouseCode: "USS",
        auctionHouseName: "ユー・エス・エス",
        auctionDate: "2024-09-09",
        make: "マツダ",
        model: "CX-5",
        vehicleRegistrationYear: 2020,
        vehicleRegistrationMonth: 9,
        mileageKm: 58500,
        overallGrade: "5",
        exteriorGrade: "B",
        interiorGrade: "C",
        startingPrice: 1500000,
        equipmentAc: true,
        equipmentAac: true,
        equipmentNav: true,
        frontBumperDefects: "A1",
        frontLeftDoorDefects: "B2",
        rearRightFenderDefects: "U1",
        totalDefectCount: 3,
        inspectorComments: "ナビ備品車内、無ければ欠品",
        auctionStatus: "upcoming",
        isExportEligible: true,
        dataSource: "sample_data",
        qualityScore: 8,
      },
      {
        lotNumber: "2047",
        auctionHouseCode: "TAA",
        auctionHouseName: "トヨタオートオークション",
        auctionDate: "2024-09-10",
        make: "トヨタ",
        model: "プリウス",
        vehicleRegistrationYear: 2019,
        vehicleRegistrationMonth: 3,
        mileageKm: 45200,
        overallGrade: "4.5",
        exteriorGrade: "A",
        interiorGrade: "B",
        startingPrice: 1800000,
        equipmentAc: true,
        equipmentAac: true,
        equipmentNav: true,
        equipmentAbs: true,
        equipmentAirbag: true,
        frontBumperDefects: "A1",
        totalDefectCount: 1,
        inspectorComments: "ハイブリッド車、燃費良好",
        auctionStatus: "upcoming",
        isExportEligible: true,
        dataSource: "sample_data",
        qualityScore: 9,
      },
      {
        lotNumber: "3158",
        auctionHouseCode: "USS",
        auctionHouseName: "ユー・エス・エス",
        auctionDate: "2024-09-11",
        make: "ホンダ",
        model: "フィット",
        vehicleRegistrationYear: 2021,
        vehicleRegistrationMonth: 7,
        mileageKm: 32800,
        overallGrade: "4",
        exteriorGrade: "B",
        interiorGrade: "A",
        startingPrice: 1200000,
        equipmentAc: true,
        equipmentPs: true,
        equipmentPw: true,
        equipmentAbs: true,
        frontLeftDoorDefects: "U1",
        rearBumperDefects: "A1",
        totalDefectCount: 2,
        inspectorComments: "コンパクトカー、市内走行中心",
        auctionStatus: "sold",
        finalPrice: 1350000,
        isExportEligible: true,
        dataSource: "sample_data",
        qualityScore: 7,
      },
      {
        lotNumber: "4269",
        auctionHouseCode: "JAA",
        auctionHouseName: "JAAオートオークション",
        auctionDate: "2024-09-12",
        make: "ニッサン",
        model: "ノート",
        vehicleRegistrationYear: 2022,
        vehicleRegistrationMonth: 1,
        mileageKm: 15600,
        overallGrade: "5",
        exteriorGrade: "A",
        interiorGrade: "A",
        startingPrice: 1600000,
        equipmentAc: true,
        equipmentAac: true,
        equipmentNav: true,
        equipmentAbs: true,
        equipmentAirbag: true,
        equipmentSr: true,
        totalDefectCount: 0,
        inspectorComments: "ほぼ新車状態、サンルーフ付き",
        auctionStatus: "upcoming",
        isExportEligible: true,
        dataSource: "sample_data",
        qualityScore: 10,
      },
      {
        lotNumber: "5371",
        auctionHouseCode: "MOTA",
        auctionHouseName: "モタ",
        auctionDate: "2024-09-13",
        make: "スバル",
        model: "インプレッサ",
        vehicleRegistrationYear: 2018,
        vehicleRegistrationMonth: 11,
        mileageKm: 72300,
        overallGrade: "3.5",
        exteriorGrade: "C",
        interiorGrade: "B",
        startingPrice: 950000,
        equipmentAc: true,
        equipmentPs: true,
        equipmentPw: true,
        equipmentAbs: true,
        equipmentAw: true,
        frontBumperDefects: "B2",
        frontLeftFenderDefects: "U1",
        rearLeftDoorDefects: "A1",
        interiorDefects: "W1",
        totalDefectCount: 4,
        inspectorComments: "AWD、アルミホイール付き",
        auctionStatus: "unsold",
        isExportEligible: false,
        dataSource: "sample_data",
        qualityScore: 6,
      },
    ];

    const insertedIds = [];
    for (const sheet of sampleAuctionSheets) {
      const id = await ctx.db.insert("auctionSheets", sheet);
      insertedIds.push(id);
    }

    return { 
      message: `Successfully inserted ${insertedIds.length} sample auction sheets`,
      insertedIds 
    };
  },
});